title: Orion Protocol
email: joaquin.softdev@gmail.com
description: >- 
url: "https://fullbuster-t.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  fullbuster-t
timezone: America/Mexico_City

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

pagination:
  enabled: true
  per_page: 5
  permalink: /page:num/
  sort_reverse: true

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: /category/:name/
    tag: /tag/:name/

# highlighter: rouge
# markdown: kramdown
# kramdown:
#   syntax_highlighter_opts:
#      block:
#        line_numbers: true